### ISSUE TITLE
error with slf4j: ambiguous reference to overloaded definition

### ISSUE THREAD

**Issue by giabao** [typesafehub/scalalogging#16]
build.sbt:

```
version := "0.1"

name := "scalalogging"

scalaVersion := "2.10.0"

libraryDependencies += "com.typesafe" %% "scalalogging-slf4j" % "1.0.0"
```

src/main/scala/Main.scala:

``` scala
import com.typesafe.scalalogging.slf4j.Logging

object Main extends App with Logging{
  logger.info("Hi: {}, {}", "foo", "bar")
}
```

$ sbt  compile =>

```
[error] /home/giabao/o/dev/test-projects/scalalogging/src/main/scala/Main.scala:4: ambiguous reference to overloaded definition,
[error] both method info in trait Logger of type (x$1: String, x$2: <repeated...>[Object])Unit
[error] and  method info in trait Logger of type (x$1: String, x$2: Any, x$3: Any)Unit
[error] match argument types (String,String,String)
[error]   logger.info("Hi: {}, {}", "foo", "bar")
[error]              ^
[error] one error found
[error] (compile:compile) Compilation failed
```

**Comment by hseeberger** [comment]
Wow. This is a tricky one. Not directly related to ScalaLogging or Macros. See http://groups.google.com/group/scala-language/browse_thread/thread/9ace08548bbec46c

Working on a workaround ...

**Comment by hseeberger** [comment]
Fixed in 1.0.1. Please give it a try.

**Comment by Johnlon** [comment]
For the record its all more complicated and messy in user-land than the various posts I've seen on this issue might indicate ...

Had a problem this week where a test compiled fine under Scala 10 but failed to compile on 11.

The line in question was calling the slf4j api ...

``` scala
  logger.debug("hello {} / {} ", "Hello", "World")
```

What we see is ...

``` scala
C:\working\dev\work\ops\incubator\commons-incubator\commons-core\src\test\scala\Fail.scala:14: ambiguous reference to overloaded definition,
both method debug in trait Logger of type (x$1: String, x$2: <repeated...>[Object])Unit
and  method debug in trait Logger of type (x$1: String, x$2: Any, x$3: Any)Unit
match argument types (String,String,String)
  logger.debug("hello {} / {} ", "Hello", "World")
```

As discussed elsewhere the underlying problem is scala having a problem with method resolution vs the Java api where we have the following alternatives...

``` scala
public void debug(String format, Object arg1, Object arg2);
public void debug(String format, Object... arguments); 
```

Directly calling the api with 3 anyref args from Scala is not supported due to the scala compiler being unable to tell the difference between these two methods on the slf4j API.

There is some more discussion on this point here .. 
// http://webcache.googleusercontent.com/search?q=cache:X_c1vUR32NMJ:https://groups.google.com/d/topic/scala-language/ms4IVIu-xGw+&cd=1&hl=en&ct=clnk&gl=uk

Obviously Java doesn’t have this problem – strike against scala!!

Also it's not clear why there is no confusion with the  2 arg api that also exists ...

``` scala
public void debug(String format, Object argument);
...vs ...
public void debug(String format, Object arg1, Object arg2);
public void debug(String format, Object... arguments);
```

However – we are only seeing this problem in Scala 11 and not 10.
Why does it work on scala 10???
Turns out there is some scala compiler Evil going on.
The bit of code that was causing these issues was a test and scalatest contains a fragment like the one shown below. The presence of this magic causes scala 10 to compile ok, but not 11. Note that magic this code doesn’t even get incorporated but despite that it causes 10 to pass the build!!!!?

``` scala
implicit def convertToAnyRef[T](left: T): AnyRef = {
    ??? // NEVER EVEN CALLED - BUT PERSUADES THE COMPILER TO RESOLVE THE CORRECT 3 ARG debug METHOD
  }
```

Possible solution ??
There is a way to hint scala 11 and 10 to pass the compile ...

``` scala
  logger.debug("hello {} / {} ", "Hello":Any, "World":Any) 
```

All a bit nasty.

Try it yourself - compile the following on scala 10 and 11 (you'll need the slf4j-api dependency).

``` scala
class CompilesOn_Neither_10_Nor_11  {
  val logger: org.slf4j.Logger = null

  logger.debug("hello {} / {} ", "Hello", "World")
}

class CompilesOn_10_ButNot_11 {
  implicit def convertToAnyRef[T](left: T): AnyRef = {
    // NEVER CALLED - BUT PERSUADES THE COMPILER TO RESOLVE THE CORRECT debug(String,Object,Object) METHOD
    // An incantation with the same affect as this exists in scalatest Suite so a scalatest like this would work on 10 but not 11
    ???
  }

  val logger: org.slf4j.Logger = null

  logger.debug("hello {} / {} ", "Hello", "World")
}

object CompilesOn_10_And_11 {
  val logger: org.slf4j.Logger = null

  logger.debug("hello {} / {} ", "Hello":Any, "World":Any)
}
```

**Comment by techmag** [comment]
FYI: Forcing just the last argument to be an Any resolves the compiler's issue(s) and makes for slightly less code...

  logger.debug("hello {} / {} ", "Hello", "World":Any)

**Comment by arroadie** [comment]
Getting late to this, I think, but you may also do

``` scala
logger.debug("hello {} {} {} {} {}", Array("from", "all", "the", "elements", "here"):_*)
```

as the casting of any on all elements may sound repetitive.

**Comment by jonathon-bell** [comment]
...or just add a 3rd parameter:

logger.debug("hello {} / {} ", "Hello", "World",**""**)

**Comment by jeff303** [comment]
> Getting late to this, I think, but you may also do
> 
> ```scala
> logger.debug("hello {} {} {} {} {}", Array("from", "all", "the", "elements", "here"):_*)
> ```
> 
> as the casting of any on all elements may sound repetitive.

I'm getting 

```
Error:(56, 54) no `: _*' annotation allowed here
(such annotations are only allowed in arguments to *-parameters)
          Array(param1, param2, param3, param4):_*
```

with this code

```
log.warn(
  "long warning message with four params {} {} {} {}",
  Array(param1, param2, param3, param4):_*
)
```

on Scala 2.11.8.  If I don't use the `Array` wrapper at all, i.e.

```
log.warn(
  "long warning message with four params {} {} {} {}",
  param1,
  param2,
  param3,
  param4
)
```

then the error is

```
Error:(55, 11) overloaded method value warn with alternatives:
  (x$1: org.slf4j.Marker,x$2: String,x$3: Object*)Unit <and>
  (x$1: String,x$2: Object*)Unit
 cannot be applied to (String, String, Long, Long, Long)
      log.warn(
```

I don't quite understand that, since the first param is clearly a `String` (as detected by the compiler), so I don't get how the first alternative it lists would be under consideration (since its first parameter type is `org.slf4j.Marker`).
